version: "3.9"
services:
    cmcd-server:
        container_name: cmcd-server
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ../cmcd-server/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ../cmcd-server/nginx/cmcd_njs.js:/etc/nginx/cmcd_njs.js:ro
            - ../cmcd-server/nginx/media/:/etc/nginx/media/:ro

    cmcd-bridge:
        build: ../cmcd-bridge/
        image: cmcd-bridge
        container_name: cmcd-bridge
        ports:
            - "8088:8088"
        volumes:
            - ./../cmcd-bridge/:/usr/src/cmcd-bridge
        depends_on:
            - mysql
            - cmcd-server

    mysql:
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: user
            MYSQL_ROOT_PASSWORD: password
        command: [
            "mysqld",
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--disabled-storage-engines=MEMORY,FEDERATED"
        ]

    grafana:
        build: ../grafana/
        image: grafana-with-mongo
        ports:
            - "3000:3000"
            - "3333:3333" # to debug mongodb-grafana plugin
        environment:
            GF_USERS_ALLOW_SIGN_UP: false
            GF_AUTH_ANONYMOUS_ENABLED: true
            GF_AUTH_ANONYMOUS_ORG_ROLE: Editor
        restart: always
