version: "3.9"
services:
    cmcd-server:
        container_name: cmcd-server
        image: nginx:latest
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ../cmcd-server/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ../cmcd-server/nginx/cmcd_njs.js:/etc/nginx/cmcd_njs.js:ro
            - ../cmcd-server/nginx/media/:/etc/nginx/media/:ro
        depends_on:
            - cmcd-bridge

    cmcd-bridge:
        build: ../cmcd-bridge/
        image: cmcd-bridge
        container_name: cmcd-bridge
        restart: always
        ports:
            - "8088:8088"
        volumes:
            - ./../cmcd-bridge/server.js:/usr/src/cmcd-bridge/server.js
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: user
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./../database/:/docker-entrypoint-initdb.d
        command: [
            "mysqld",
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--disabled-storage-engines=MEMORY,FEDERATED"
        ]

    grafana:
        image: grafana/grafana-oss:9.3.6
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./../grafana/provisioning/:/etc/grafana/provisioning/
        environment:
            GF_USERS_ALLOW_SIGN_UP: false
            GF_AUTH_ANONYMOUS_ENABLED: true
            GF_AUTH_ANONYMOUS_ORG_ROLE: Editor
        depends_on:
            - mysql

    locust:
        build: ../load-test
        image: load-test
        ports:
            - "8089:8089"