version: "3.9"
services:
    cmcd-server:
        container_name: cmcd-server
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ../cmcd-server/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ../cmcd-server/nginx/cmcd_njs.js:/etc/nginx/cmcd_njs.js:ro
            - ../cmcd-server/nginx/media/:/etc/nginx/media/:ro
    mongo:
        image: mongo:6.0
        ports:
            - "27017:27017"

    grafana:
        build: ../grafana/
        image: grafana-with-mongo
        ports:
            - "3000:3000"
            - "3333:3333" # to debug mongodb-grafana plugin
        environment:
            GF_USERS_ALLOW_SIGN_UP: false
            GF_AUTH_ANONYMOUS_ENABLED: true
            GF_AUTH_ANONYMOUS_ORG_ROLE: Editor
        restart: always

    # Fore easy access to mongo during development
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_URL: "mongodb://mongo:27017/"
        depends_on:
            - mongo
